### ISSUE TITLE
Error on Windows 10: Invalid auth token

### ISSUE THREAD

**Issue by gokaygurcan** [graphcool/graphcool-cli#119]
Hello,

I'm trying to use Graphcool but can't get authenticated/initiated the project. Here's the output that I see:

```bash
C:\Users\gokay\Documents\Projects\gql
λ graphcool init
×  Error: Invalid auth token
  graphcool Error: Invalid auth token
  graphcool     at Object.<anonymous> (C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\dist\src\commands\auth.js:38:15)
  graphcool     at Generator.next (<anonymous>)
  graphcool     at fulfilled (C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\dist\src\commands\auth.js:4:58)
  graphcool     at <anonymous> +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/


C:\Users\gokay\Documents\Projects\gql
λ npm uninstall -g graphcool
removed 137 packages in 5.184s

C:\Users\gokay\Documents\Projects\gql
λ npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gokay\AppData\Roaming\npm-cache\_logs\2017-06-30T10_22_31_417Z-debug.log

C:\Users\gokay\Documents\Projects\gql
λ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

C:\Users\gokay\Documents\Projects\gql
λ npm install -g graphcool
C:\Users\gokay\AppData\Roaming\npm\gc -> C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\dist\src\index.js
C:\Users\gokay\AppData\Roaming\npm\graphcool -> C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\dist\src\index.js

> graphcool@1.1.1 postinstall C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool
> echo Run graphcool init to get started

Run graphcool init to get started
added 136 packages in 29.008s

C:\Users\gokay\Documents\Projects\gql
λ graphcool init
×  Error: Invalid auth token
  graphcool Error: Invalid auth token
  graphcool     at Object.<anonymous> (C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\dist\src\commands\auth.js:38:15)
  graphcool     at Generator.next (<anonymous>)
  graphcool     at fulfilled (C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\dist\src\commands\auth.js:4:58)
  graphcool     at <anonymous> +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

I'm on Windows 10 (version 1607), my node version is v8.0.0 and npm version is v5.0.0.

The result is the same if I use `graphcool auth --token "auth_string"`.

Feel free to ask if you need more information. Thanks in advance!

G.

**Comment by gokaygurcan** [comment]
Hi again,

Just updated my Node.js and npm versions to 8.1.3 and 5.0.4 respectively. Still getting the same error.

**Comment by schickling** [comment]
Thanks a lot for providing all this context @gokaygurcan. Unfortunately we don't have immediate access to a Windows 10 machine, do you have the possibility to reproduce this behaviour on a different computer running Windows 10?

**Comment by gokaygurcan** [comment]
Hi again,

We investigated the problem internally and found that ESET is blocking the HTTP post or the returned data. It's not important at which level this is happening though. 

We put a `console.log` after this line: https://github.com/graphcool/graphcool-cli/blob/e3dce730ec18752d047e2d9f7e47f35595e5ad41/src/api/GraphcoolAuthServer.ts#L70

Here's the result: 

```bash
{ Error
    at ClientRequest.<anonymous> (C:\Users\gokay\AppData\Roaming\npm\node_modules\graphcool\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:392:12)
    at onwrite (_stream_writable.js:414:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at TLSSocket.Socket._destroy (net.js:556:3)
    at TLSSocket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:853:10)
  name: 'FetchError',
  message: 'request to https://api.graph.cool/system failed, reason: write EPROTO 101057795:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:openssl\\ssl\\s23_clnt.c:772:\n',
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO' }
```

Then, we put another `console.log` after https://github.com/graphcool/graphcool-cli/blob/e3dce730ec18752d047e2d9f7e47f35595e5ad41/src/api/GraphcoolAuthServer.ts#L61 to see what is the returned value, and here's the data:

```bash
Body {
  url: 'https://api.graph.cool/system',
  status: 403,
  statusText: 'Blocked by ESET Security',
  headers:
   Headers {
     _headers:
      { 'content-type': [Array],
        'content-length': [Array],
        connection: [Array] } },
  ok: false,
  body:
   PassThrough {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 15875,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: { end: [Object] },
     _eventsCount: 1,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _transformState:
      TransformState {
        afterTransform: [Function],
        needTransform: false,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer' } },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false }
```

---

As you can clearly see above, it's *Blocked by ESET Security*. 

I'm now trying to convince our SYSAdmins to add graph.cool domain and its subdomains into the whitelist. Please keep this issue open until then. After that I'll write another update and let you know if problem is solved or not. 

Thanks!

**Comment by gokaygurcan** [comment]
Hi,
Issue resolved after our SYSAdmins whitelisted *.graph.cool domain. 

Thanks again. Closing this issue since there's not much to do anymore.
