### ISSUE TITLE
can't install in Windows

### ISSUE THREAD

**Issue by tomByrer** [graphcool/graphcool-cli#131]
Win10, using nvm 1.1.3, node 8.2.1 64bit, npm 5.3.0

```cli
λ npm install -g graphcool
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\tom-byrer\AppData\Roaming\nvm\v8.2.1\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
module.js:487
    throw err;
    ^
```

**Comment by marktani** [comment]
That seems to be a common error message when something in your npm install is corrupted. Maybe try this suggested approach: https://stackoverflow.com/a/41000891/1176596?
