### ISSUE TITLE
graphcool init returns unexpected token 

### ISSUE THREAD

**Issue by gregory-h** [graphcool/graphcool-cli#138]
Completely new to graphcool so apologies if this is a noob comment...

npm install -g graphcool
mkdir gctest; cd gctest 
graphcool init 

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Assuming this is a babel setup issue but not sure how to resolve.

Also tried using sudo npm install -g graphcool with same result.

Ubuntu 16.04
node v4.2.6
npm v3.5.2

**Comment by marktani** [comment]
Hey, this is related to your node version, could you upgrade to a more recent one?

**Comment by gregory-h** [comment]
Ah that worked thank you
