### ISSUE TITLE
[1.3.7]  Whoops, something went wrong while creating the project.

### ISSUE THREAD

**Issue by conradwt** [graphcool/graphcool-cli#190]
Hi, I'm getting the following error:

```
$ graphcool init --schema https://grapqlbin.com/hn-relay.graphql --name Hackernews
Whoops, something went wrong while creating the project.

✖  Error: request to https://grapqlbin.com/hn-relay.graphql failed, reason: connect ECONNREFUSED 104.239.207.44:443
  graphcool FetchError: request to https://grapqlbin.com/hn-relay.graphql failed, reason: connect ECONNREFUSED 104.239.207.44:443
  graphcool     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/node-fetch/index.js:133:11)
  graphcool     at emitOne (events.js:115:13)
  graphcool     at ClientRequest.emit (events.js:210:7)
  graphcool     at TLSSocket.socketErrorListener (_http_client.js:401:9)
  graphcool     at emitOne (events.js:115:13)
  graphcool     at TLSSocket.emit (events.js:210:7)
  graphcool     at emitErrorNT (internal/streams/destroy.js:64:8)
  graphcool     at _combinedTickCallback (internal/process/next_tick.js:138:11)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:218:9) +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

BTW, I'm on the second step of the following tutorial:

https://www.youtube.com/watch?v=I6I2Y-t7tGI&t=86

Finally, I have the following setup:

- macOS 10.13 Beta 9
- Node v8.4.0
- Graphcool 1.3.7

**Comment by conradwt** [comment]
There was an typo and this issue can closed.
