### ISSUE TITLE
Error after installing latest beta

### ISSUE THREAD

**Issue by danmkent** [graphcool/graphcool-cli#247]
After installing version 1.3.16-beta7, I get the following error for all executions of the graphcool command:

```
Dans-MacBook-Pro-2:build programming$ graphcool help
/usr/local/lib/node_modules/graphcool/node_modules/rwlockfile/lib/rwlockfile.js:9
async function pidActive(pid) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Plugin/Lock.ts:2:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by timsuchanek** [comment]
Thanks for reporting! Which node version are you using?

**Comment by danmkent** [comment]
An update of node solve the problem - this issue can be closed - thanks!
