### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool-cli#93]
> Copying over @JPinlac's issue from https://github.com/graphcool/graphcool-cli/issues/88#issuecomment-307213314

Trying to follow the quickstart-with-apollo with angular, the step *graphcool init --schema http://graphqlbin.com/instagram.graphql* errors out during authentication. 
```
  graphcool Error: Whoops, something went wrong during authentication.
  graphcool
  graphcool     at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:26:19)
  graphcool     at throw (native)
  graphcool     at rejected (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:5:65)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:129:7) +0ms
```

**Comment by nikolasburk** [comment]
Can you confirm this is still an issue? I can't reproduce this, authentication does work for me. Maybe this was a tmp backend issue?

**Comment by JPinlac** [comment]
It is an issue with my network during authentication. Is there anyway to specify a proxy for the CLI?
```
graphcool auth
⠦ You need to authenticate. Your browser will open shortly...✖  Error: Whoops, something went wrong during authentication.
  graphcool Error: Whoops, something went wrong during authentication.
  graphcool
  graphcool     at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:26:19)
  graphcool     at throw (native)
  graphcool     at rejected (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:5:65)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:129:7) +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

**Comment by marktani** [comment]
Let's discuss potential solutions here #90. 🙂
