### ISSUE TITLE
Token based authentication graphcoolrc error

### ISSUE THREAD

**Issue by JPinlac** [graphcool/graphcool-cli#94]
When trying to authenticate using tokens `graphcool auth -t <token>` the following error occurs. 

```
graphcool auth -t eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ...
✖  Error: ENOENT: no such file or directory, unlink '/Users/jpinlac/.graphcoolrc'
  graphcool Error: ENOENT: no such file or directory, unlink '/Users/jpinlac/.graphcoolrc'
  graphcool     at Error (native)
  graphcool     at Object.fs.unlinkSync (fs.js:1089:18)
  graphcool     at FileSystemResolver.delete (/usr/local/lib/node_modules/graphcool/dist/src/system/FileSystemResolver.js:14:12)
  graphcool     at Object.deleteGraphcoolConfig (/usr/local/lib/node_modules/graphcool/dist/src/utils/file.js:76:20)
  graphcool     at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:36:16)
  graphcool     at next (native)
  graphcool     at fulfilled (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:4:58)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:129:7) +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

After adding the .graphcoolrc to my home directory, the following error occurs when retrying auth.

```
graphcool auth -t eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ...
✖  Error: Unexpected end of JSON input
  graphcool SyntaxError: Unexpected end of JSON input
  graphcool     at Object.parse (native)
  graphcool     at shouldDisplayQuickstart (/usr/local/lib/node_modules/graphcool/dist/src/index.js:202:30)
  graphcool     at /usr/local/lib/node_modules/graphcool/dist/src/index.js:41:35
  graphcool     at next (native)
  graphcool     at /usr/local/lib/node_modules/graphcool/dist/src/index.js:8:71
  graphcool     at __awaiter (/usr/local/lib/node_modules/graphcool/dist/src/index.js:4:12)
  graphcool     at main (/usr/local/lib/node_modules/graphcool/dist/src/index.js:36:12)
  graphcool     at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/dist/src/index.js:222:1)
  graphcool     at Module._compile (module.js:570:32)
  graphcool     at Object.Module._extensions..js (module.js:579:10)
  graphcool     at Module.load (module.js:487:32)
  graphcool     at tryModuleLoad (module.js:446:12)
  graphcool     at Function.Module._load (module.js:438:3)
  graphcool     at Module.runMain (module.js:604:10)
  graphcool     at run (bootstrap_node.js:394:7)
  graphcool     at startup (bootstrap_node.js:149:9)
  graphcool     at bootstrap_node.js:509:3 +0ms

 * You can enable additional output by setting `export DEBUG=graphcool` and rerunning the command.
 * Open an issue on GitHub: https://github.com/graphcool/graphcool-cli.
 * Get in touch if you need help: http://slack.graph.cool/
```

**Comment by marktani** [comment]
Where did you obtain the token from?

**Comment by JPinlac** [comment]
The token is from the project's setting page under authentication. I truncated the whole token for the post.

**Comment by JPinlac** [comment]
The token is from the project's setting page under authentication. I
truncated the whole token for the post.

On Mon, Jun 12, 2017 at 10:55 AM, Nilan Marktanner <notifications@github.com

**Comment by marktani** [comment]
You need to supply a different token, we'll soon publish documentation on how to do this exactly. I'll update this issue then.

**Comment by schickling** [comment]
@JPinlac please hard-reload the console and recheck the settings page 🙂

**Comment by JPinlac** [comment]
Nice! So that auth command works, but it doesn't work behind a firewall.

After authenticating on a regular network, I see that the .graphcoolrc is updated with the token. After retrying the same token authentication command while behind the firewall I receive the following error and find that the .graphcoolrc is deleted:

```
graphcool auth --token "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0OTcwMTU1MjIsImNsaWVudElkIjoiY2ozb3M3Mjgwb3VsMDAxOTgxZjZzc2oxbiJ9.wfSejvKsbl7olWGPRqdtMt18B81W8eS5dkFEiv8MRpE"
✖  Error: Invalid auth token
  graphcool Error: Invalid auth token
  graphcool     at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:37:15)
  graphcool     at next (native)
  graphcool     at fulfilled (/usr/local/lib/node_modules/graphcool/dist/src/commands/auth.js:4:58)
  graphcool     at process._tickDomainCallback (internal/process/next_tick.js:129:7) +0ms
```
Running the command a subsequent time gives me same error as before.

**Comment by marktani** [comment]
@JPinlac I just adjusted the token you posted. You should keep it safe 🙂 
Is the issue with the firewall the same as being discussed in #90?

**Comment by JPinlac** [comment]
I was hoping the token authentication would bypass the need for a proxy, so
yeah it's the same issue.

On Tue, Jun 13, 2017 at 10:21 AM, Nilan Marktanner <notifications@github.com

**Comment by marktani** [comment]
Let's continue the discussion in #90 then 👍
